DWAPlannerROS:
  max_vel_x: 0.5
  min_vel_x: 0.1
  max_vel_theta: 1.5
  min_vel_theta: -1.5
  acc_lim_x: 0.5
  acc_lim_theta: 1.5
  xy_goal_tolerance: 0.2
  yaw_goal_tolerance: 0.1
  sim_time: 1.5
  vx_samples: 10
  vtheta_samples: 20
  path_distance_bias: 32.0
  goal_distance_bias: 24.0
  obstacle_cost_scale: 0.5
  stop_time_buffer: 0.2