map_type: costmap
use_sim_time: True
obstacle_range: 2.5
raytrace_range: 3.0
#footprint: [[0.2225, 0.2045], [0.2225, -0.2045], [-0.2225, -0.2045], [-0.2225,0.2045]] # Robot footprint
robot_radius: 0.3
inflation_radius: 0.6
transform_tolerance: 5.0
observation_sources: laser_scan_sensor
laser_scan_sensor: {sensor_frame: hokuyo_frame, data_type: LaserScan, topic: /hokuyo, marking: true, clearing: true}