map_type: costmap
use_sim_time: True
obstacle_range: 2.5
raytrace_range: 3.0
transform_tolerance: 0.2
observation_sources: laser_scan_sensor
laser_scan_sensor: {sensor_frame: hokuyo_frame, data_type: LaserScan, topic: /hokuyo, marking: true, clearing: true}